"""your_message_here

Revision ID: 6718332a3703
Revises: b8cf3d788230
Create Date: 2026-01-03 14:53:15.077758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6718332a3703'
down_revision: Union[str, Sequence[str], None] = 'b8cf3d788230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmdb_selected')
    op.drop_table('tmdb_movies_raw')
    op.drop_table('tmdb_credits_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmdb_credits_raw',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cast', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crew', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tmdb_movies_raw',
    sa.Column('budget', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('homepage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('popularity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('production_companies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('production_countries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('runtime', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('spoken_languages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tmdb_movies_raw_pkey'))
    )
    op.create_table('tmdb_selected',
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cast', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crew', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('director_name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
