"""your_message_here

Revision ID: b0aee7f25628
Revises: a3228949a02b
Create Date: 2026-01-03 02:36:50.300618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aee7f25628'
down_revision: Union[str, Sequence[str], None] = 'a3228949a02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_ratings', sa.Column('rated_at', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'description')
    op.drop_column('movie_ratings', 'rated_at')
    # ### end Alembic commands ###
